### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nicewook** [nicewook/whatever#1]
# customize posh-git

- [ ] Know how to manipulate
- [ ] List the wanted format
- [ ] make it with some unicode
